# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_packages:
  - ggplot2
addons:
  apt:
    update: true
    packages: 
      - libfftw3-3
      - libfftw3-dev
      - libsndfile1
      - libsndfile1-dev